#+TITLE: Dai-ikkyo (group 1) - Setting up the environment

* Resources
The best resource for getting started is at
[[http://www.erlang.org/download.html][The erlang download page]]

* Operating Systems specific information

** Windows
Download the 32 / 64 bit binary from the erlang download page
linked above.
Follow the usual install procedure.

*** Optional
Install emacs and follow the instructions for setting up
emacs and erlang described below

** MAC OSX
Use your preferred package manage ports / brew to install

~sudo port install erlang~

alternatively the Erlang Solutions link below in the *nix
instructions have a OSX package that can be downloaded and
installed.

** *nix environments

*** Package manager

All major distributions and the BSD's have an erlang package.
BSD's tend to be more current but linux package distributions
can lag some way behind the current release.

*** Erlang Solutions

[[https://www.erlang-solutions.com/downloads/download-erlang-otp][Erlang Solutions]]
have a binary or repository entry that you can use to get
the latest version of Erlang installed.

* Emacs

The erlang distribution comes with an emacs mode that makes
erlang development in emacs a pleasure.

Instructions for setting it up can be found on the 
[[http://www.erlang.org/doc/apps/tools/erlang_mode_chapter.html][emacs mode]]
section of the erlang website.




